
import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication } from '@nestjs/common';
import * as supertestLib from 'supertest';
import { AppModule } from './../src/app.module';
import { CACHE_MANAGER } from '@nestjs/cache-manager';
import { Cache } from 'cache-manager';

// Handle supertest import for CommonJS / ESM interop
const supertest = (supertestLib as any).default ?? supertestLib;

/**
 * Pro-Grade Regression Suite for my-microservice
 *
 * This file is auto-generated by candy-nest-cli based on your selected features.
 * It performs live integration tests against the Docker infrastructure defined
 * in docker-compose.yml.
 *
 * Run with:  npm run test:e2e
 *
 * Prerequisites:
 *   - docker-compose up -d (all containers healthy)
 *   - .env configured with correct host/port values
 */
describe('my-microservice — Regression (e2e)', () => {
  let app: INestApplication;
  let cacheManager: Cache;


  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();

    await app.init();

    cacheManager = app.get<Cache>(CACHE_MANAGER);

  }, 60000); // Allow 60s for DB connections to establish

  afterAll(async () => {
    if (app) await app.close();
  }, 60000);


  // ─── Health & Observability ────────────────────────────────────────────────

  describe('Infrastructure Health', () => {
    it('/health (GET) — endpoint is reachable and reports ok', async () => {
      const res = await supertest(app.getHttpServer()).get('/health');

      // Terminus returns 200 (ok) or 503 (degraded). We accept both since
      // the endpoint itself functioning proves the health module is wired correctly.
      expect([200, 503]).toContain(res.status);
      expect(['ok', 'error', 'shutting_down']).toContain(res.body.status);
    });

    it('/metrics (GET) — Prometheus metrics are exposed', () => {
      return supertest(app.getHttpServer())
        .get('/metrics')
        .expect(200)
        .expect((res: any) => {
          expect(res.text).toContain('nodejs_version_info');
          expect(res.text).toContain('process_cpu_seconds_total');
        });
    });

  });



  // ─── Polyglot Persistence ─────────────────────────────────────────────────

  describe('Database CRUD', () => {

    it('PostgreSQL (TypeORM) — full create/read/delete lifecycle', async () => {
      const created = await supertest(app.getHttpServer())
        .post('/examples/postgres')
        .send({ name: 'regression-test' })
        .expect(201);

      const { id } = created.body;
      expect(id).toBeDefined();

      await supertest(app.getHttpServer())
        .get(`/examples/postgres/${id}`)
        .expect(200)
        .expect((res: any) => expect(res.body.id).toBe(id));

      await supertest(app.getHttpServer())
        .delete(`/examples/postgres/${id}`)
        .expect(200);
    });



  });



  // ─── Cache Layer ──────────────────────────────────────────────────────────

  describe('Redis Cache', () => {
    it('should set and retrieve a cached value', async () => {
      const key = 'my-microservice-regression-cache';
      const value = { ok: true, ts: Date.now() };

      await cacheManager.set(key, value, 10);
      const retrieved = await cacheManager.get(key);

      expect(retrieved).toEqual(value);

      // Cleanup
      await cacheManager.del(key);
    });
  });





  // ─── Kafka Connectivity ───────────────────────────────────────────────────
  // Note: Full Kafka round-trip tests require a running broker and the
  // topics defined in docker-compose.yml to be created by kafka-init.
  // The health endpoint's 'messaging' indicator covers broker reachability.

  describe('Kafka', () => {
    it('health endpoint includes messaging indicator', async () => {
      const res = await supertest(app.getHttpServer()).get('/health');
      expect([200, 503]).toContain(res.status);
      // If messaging key is present, verify it has a status field
      const messaging = res.body.info?.messaging ?? res.body.details?.messaging;
      if (messaging) {
        expect(messaging.status).toBeDefined();
      }
    });
  });



});
